version: '3'

services:
  nodeproject:
    build:
      context: .
      args:
        - NODE_ENV=dev
    volumes:
    - ./:/app
    - /app/node_modules
    env_file:
    - ./.env
    command: npm run dev